title: "John Devlin - User experience / UX designer and front-end developer, based in Belfast, Northern Ireland."
email: "j@johndevlin.me"
url: "http://johndevlin.me"
twitter_username: "john_devlin"
github_username: "johndevlin"
permalink: "pretty"
