title: "John Devlin - Product designer based in Belfast, Northern Ireland, specialising in UX / UI design, front-end development and creating user-friendly, accessible interfaces"
description: "John Devlin - Product designer based in Belfast, Northern Ireland, specialising in UX / UI design, front-end development and creating user-friendly, accessible interfaces"
email: "j@johndevlin.me"
url: "http://johndevlin.me"
twitter_username: "john_devlin"
github_username: "johndevlin"
permalink: "pretty"
